In [2]:
# Importing the NumPy library
import numpy as np

# 1. Creating Arrays

In [2]:
# Creating a 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]


In [ ]:
# Creating a 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

In [ ]:
# Creating Arrays with Default Values
zeros = np.zeros((3, 3))  # 3x3 matrix of zeros
ones = np.ones((2, 2))  # 2x2 matrix of ones
identity = np.eye(3)  # 3x3 identity matrix

In [ ]:

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

In [ ]:
# Creating an Array with a Range of Values
arr_range = np.arange(0, 10, 2)  # From 0 to 10 with step size 2
print("Range Array:", arr_range)

In [ ]:
# Creating an Array with Linearly Spaced Values
arr_linspace = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print("Linspace Array:", arr_linspace)

# 2. Array Shape and Reshaping

In [ ]:
# Check Shape of an Array
print("Shape of arr2:", arr2.shape)

In [ ]:
# Reshape Array (Changing Dimensions)
reshaped = arr1.reshape((5, 1))
print("Reshaped Array:\n", reshaped)

In [ ]:
# Flatten a Multi-dimensional Array to 1D
flattened = arr2.flatten()
print("Flattened Array:", flattened)

# 3. Basic Array Operations

In [ ]:
# Element-wise Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

In [ ]:
# Aggregate Functions
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Standard Deviation:", np.std(a))
print("Max:", np.max(a))
print("Min:", np.min(a))

# 4. Indexing and Slicing

In [ ]:
# Accessing Elements
print("First Element of arr1:", arr1[0])
print("Element at (1, 2) in arr2:", arr2[1, 2])

In [ ]:
# Slicing
print("Slice arr1[1:4]:", arr1[1:4])

In [ ]:
# Boolean Indexing
bool_idx = arr1 > 2  # Find elements greater than 2
print("Boolean Index:", bool_idx)
print("Filtered Elements:", arr1[bool_idx])

# 5. Random Data Generation

In [6]:
# Generate Random Numbers
rand_arr = np.random.rand(3, 3)  # Uniform distribution between 0 and 1
print("Random Array:\n", rand_arr)

Random Array:
 [[0.02448281 0.35054498 0.51603793]
 [0.88880507 0.89415919 0.38094639]
 [0.79417696 0.14590177 0.34332405]]


In [4]:
# Generate Random Integers
rand_int = np.random.randint(1, 10, (2, 2))  # Integers between 1 and 9
print("Random Integers:\n", rand_int)

Random Integers:
 [[7 3]
 [2 6]]


In [7]:
# Set Seed for Reproducibility
np.random.seed(42)
rand_seeded = np.random.rand(3)
print("Seeded Random Array:", rand_seeded)

Seeded Random Array: [0.37454012 0.95071431 0.73199394]


# 6. Handling NaN and Infinite Values

In [ ]:
arr_with_nan = np.array([1, np.nan, 3, np.inf])

In [ ]:
# Check for NaN and Infinite Values
print("Is NaN:", np.isnan(arr_with_nan))
print("Is Infinite:", np.isinf(arr_with_nan))

In [ ]:
# Replace NaN with 0
arr_cleaned = np.nan_to_num(arr_with_nan, nan=0.0, posinf=1000)
print("Cleaned Array:", arr_cleaned)

# 7. Linear Algebra Operations

In [ ]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", np.dot(A, B))

In [ ]:
# Transpose of a Matrix
print("Transpose:\n", A.T)

In [ ]:
# Determinant of a Matrix
print("Determinant:", np.linalg.det(A))

In [ ]:
# Inverse of a Matrix
print("Inverse:\n", np.linalg.inv(A))

# 8. Broadcasting and Vectorization

In [ ]:
# Broadcasting: Adding a scalar to an array
arr = np.array([1, 2, 3])
print("Broadcasted Addition:", arr + 5)

In [ ]:
# Vectorized Operations (Faster than loops)
arr_large = np.arange(1000000)
%timeit arr_large + 1  # Vectorized operation

In [ ]:
# Non-vectorized loop (for comparison)
def non_vectorized(arr):
    result = []
    for i in arr:
        result.append(i + 1)
    return np.array(result)

%timeit non_vectorized(arr_large)

# 9. Saving and Loading Data

In [ ]:
# Save an Array to a File
np.save('array.npy', arr1)
print("Array saved to 'array.npy'.")

In [ ]:
# Load an Array from a File
loaded_arr = np.load('array.npy')
print("Loaded Array:", loaded_arr)

In [ ]:
# Save to a CSV File
np.savetxt('array.csv', arr2, delimiter=',')
print("Array saved to 'array.csv'.")

In [ ]:
# Load from a CSV File
loaded_csv = np.loadtxt('array.csv', delimiter=',')
print("Loaded CSV Array:\n", loaded_csv)

# 10. Performance Tips and Best Practices

In [ ]:
# Use np.where for Conditional Logic
arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr % 2 == 0, 'Even', 'Odd')
print("Conditional Logic Result:", result)

In [ ]:
# Use np.concatenate to Join Arrays
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
concatenated = np.concatenate([arr_a, arr_b])
print("Concatenated Array:", concatenated)

In [ ]:
# Use np.unique to Find Unique Elements
arr = np.array([1, 2, 2, 3, 3, 3])
unique_elements = np.unique(arr)
print("Unique Elements:", unique_elements)